CREATE TABLE shipment_details
(
    id                      BIGINT primary key generated by default as identity,
    order_id                BIGINT not null,
    item_id                 BIGINT not null,
    estimated_delivery_date TIMESTAMP WITHOUT TIME ZONE,
    created_at              TIMESTAMP WITHOUT TIME ZONE,
    updated_at              TIMESTAMP WITHOUT TIME ZONE,
    status                  varchar(20),
    shipment_address        varchar not null

);


